const data = [

    {
        id : 1,
        category:'Briyani',
        info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
        price: '200',
        image:'https://media.istockphoto.com/id/1345624336/photo/chicken-biriyani.jpg?b=1&s=612x612&w=0&k=20&c=2CBPkgQI2PiNySSNi1tvwVSYFqOBgfgrgDPCyelIVrk=',
    },
    {
        id : 2,
        category:'salad',
        info: 'To make pizza, spread dough with tomato sauce, add cheese and toppings, bake until crust is golden and toppings are melted.',
        price: '300',
        image:'https://images.pexels.com/photos/434258/pexels-photo-434258.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 3,
        category:'salad',
        info: 'To make pizza, spread dough with tomato sauce, add cheese and toppings, bake until crust is golden and toppings are melted.',
        price: '300',
        image:'https://images.pexels.com/photos/764925/pexels-photo-764925.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 4,
        category:'salad',
        info: 'To make pizza, spread dough with tomato sauce, add cheese and toppings, bake until crust is golden and toppings are melted.',
        price: '300',
        image:'https://images.pexels.com/photos/2741448/pexels-photo-2741448.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 5,
        info: 'Chicken deep fry in oil',
        category: 'chicken',
        price: '100',
        image:'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
     {
        id : 6,
        info: 'Chicken deep fry in oil',
        category: 'chicken',
        price: '100',
        image:'https://images.pexels.com/photos/106343/pexels-photo-106343.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    
    {
        id : 7,
        category:'chicken',
        info: 'Cook chicken, noodles, and veggies. Sauté with garlic, ginger, soy sauce. Combine for a delicious chicken noodle stir-fry.',
        price: '150',
        image:'https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 8,
        category:'chicken',
        info: 'To prepare chili chicken, cook chicken pieces, sauté with onions, bell peppers, and a spicy chili sauce for a flavorful dish.',
        price: '180',
        image:'https://images.pexels.com/photos/2994900/pexels-photo-2994900.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 9,
        category:'pasta',
        info: 'To cook pasta, boil in salted water until al dente, then drain. Toss with sauce, herbs, and cheese for a delightful dish.',
        price: '150',
        image:'https://images.pexels.com/photos/1460872/pexels-photo-1460872.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 10,
        category:'pasta',
        info: 'To cook pasta, boil in salted water until al dente, then drain. Toss with sauce, herbs, and cheese for a delightful dish.',
        price: '150',
        image:'https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 11,
        category:'salad',
        info: 'For a veg salad, chop fresh veggies, mix with greens, and add a dressing of your choice for a healthy dish.',
        price: '99',
        image:'https://images.pexels.com/photos/718742/pexels-photo-718742.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 12,
        category:'rice',
        info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
        price: '200',
        image:'https://images.pexels.com/photos/1630495/pexels-photo-1630495.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 13,
        category:'rice',
        info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
        price: '200',
        image:'https://images.pexels.com/photos/3926124/pexels-photo-3926124.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
    {
        id : 14,
        category:'pasta',
        info: 'To cook pasta, boil in salted water until al dente, then drain. Toss with sauce, herbs, and cheese for a delightful dish.',
        price: '150',
        image:'https://images.pexels.com/photos/1527603/pexels-photo-1527603.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 15,
        category:'pasta',
        info: 'To cook pasta, boil in salted water until al dente, then drain. Toss with sauce, herbs, and cheese for a delightful dish.',
        price: '150',
        image:'https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 16,
        category:'rice',
        info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
        price: '200',
        image:'https://images.pexels.com/photos/12481168/pexels-photo-12481168.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 17,
        category:'Briyani',
        info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
        price: '200',
        image:'https://media.istockphoto.com/id/488481490/photo/fish-biryani-with-basmati-rice-indian-food.jpg?b=1&s=612x612&w=0&k=20&c=t03bdu5qcvxf2GdDvlozmXn4YfMqCkhj02IEgCm4vNo=',
    },
    {
        id : 18,
        category:'Briyani',
        info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
        price: '200',
        image:'https://media.istockphoto.com/id/1305451864/photo/biryani.jpg?b=1&s=612x612&w=0&k=20&c=fq7QvO9QZa7U8RN-l5kQi_--w4B_g5-2jUtp2NijOX8=',
    },
    {
        id : 19,
        name: "Chili Chicken",
        category:'chicken',
        info: 'To prepare chili chicken, cook chicken pieces, sauté with onions, bell peppers, and a spicy chili sauce for a flavorful dish.',
        price: '180',
        image:'https://images.pexels.com/photos/2569760/pexels-photo-2569760.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 20,
        name: "Chili Chicken",
        category:'chicken',
        info: 'To prepare chili chicken, cook chicken pieces, sauté with onions, bell peppers, and a spicy chili sauce for a flavorful dish.',
        price: '180',
        image:'https://images.pexels.com/photos/12916871/pexels-photo-12916871.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 21,
        name: "Chili Chicken",
        category:'chicken',
        info: 'To prepare chili chicken, cook chicken pieces, sauté with onions, bell peppers, and a spicy chili sauce for a flavorful dish.',
        price: '180',
        image:'https://images.pexels.com/photos/12916864/pexels-photo-12916864.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 22,
        category:'salad',
        info: 'For a veg salad, chop fresh veggies, mix with greens, and add a dressing of your choice for a healthy dish.',
        price: '99',
        image:'https://images.pexels.com/photos/361184/asparagus-steak-veal-steak-veal-361184.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 23,
        category:'salad',
        info: 'For a veg salad, chop fresh veggies, mix with greens, and add a dressing of your choice for a healthy dish.',
        price: '99',
        image:'https://images.pexels.com/photos/1247677/pexels-photo-1247677.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
    {
        id : 24,
        category:'salad',
        info: 'For a veg salad, chop fresh veggies, mix with greens, and add a dressing of your choice for a healthy dish.',
        price: '99',
        image:'https://images.pexels.com/photos/1833336/pexels-photo-1833336.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id : 25,
        name: "Pasta",
        category:'pasta',
        info: 'To cook pasta, boil in salted water until al dente, then drain. Toss with sauce, herbs, and cheese for a delightful dish.',
        price: '150',
        image:'https://images.pexels.com/photos/3214161/pexels-photo-3214161.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
    id : 26,
    name: "Pasta",
    category:'pasta',
    info: 'To cook pasta, boil in salted water until al dente, then drain. Toss with sauce, herbs, and cheese for a delightful dish.',
    price: '150',
    image:'https://images.pexels.com/photos/154145/pexels-photo-154145.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 27,
    name: "Pasta",
    category:'pasta',
    info: 'To cook pasta, boil in salted water until al dente, then drain. Toss with sauce, herbs, and cheese for a delightful dish.',
    price: '150',
    image:'https://images.pexels.com/photos/2313682/pexels-photo-2313682.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 28,
    category:'rice',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://images.pexels.com/photos/12913636/pexels-photo-12913636.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
id : 29,
category:'rice',
info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
price: '200',
image:'https://images.pexels.com/photos/9980760/pexels-photo-9980760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
},
{
    id : 30,
    category:'rice',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://images.pexels.com/photos/262897/pexels-photo-262897.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 31,
    category:'rice',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://images.pexels.com/photos/9396031/pexels-photo-9396031.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 32,
    category:'Briyani',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://images.pexels.com/photos/14731635/pexels-photo-14731635.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 33,
    category:'Briyani',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://images.pexels.com/photos/9609846/pexels-photo-9609846.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 34,
    category:'Briyani',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://images.pexels.com/photos/9738983/pexels-photo-9738983.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 35,
    category:'Briyani',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://images.pexels.com/photos/9609853/pexels-photo-9609853.jpeg?auto=compress&cs=tinysrgb&w=600',
},
{
    id : 36,
    category:'Dosai',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://tse2.mm.bing.net/th?id=OIP.8Uy-eWzp-qCwtd_9tzUfCwHaEK&pid=Api&P=0&h=180',
},
{
    id : 37,
    category:'Dosai',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://tse4.mm.bing.net/th?id=OIP.Vn9gIGPPwhqlWuPH_DgeBAHaEK&pid=Api&P=0&h=180',
},
{
    id : 38,
    category:'Dosai',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://tse3.mm.bing.net/th?id=OIP.eIpGd72F4JlFWy4v6NBGUAHaEK&pid=Api&P=0&h=180',
},
{
    id : 39,
    category:'Dosai',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://tse2.mm.bing.net/th?id=OIP.qeuvOQEQY2eOl6hBkzHuKAHaEK&pid=Api&P=0&h=180',
},
{
    id : 40,
    category:'Dosai',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://tse3.mm.bing.net/th?id=OIP.2ZPbB6FNUjDAhOxeV3kK3QHaEK&pid=Api&P=0&h=180',
},
{
    id : 41,
    category:'Dosai',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://tse3.mm.bing.net/th?id=OIP.afG5UB3b7pxF1oCtfPWQIgHaEK&pid=Api&P=0&h=180',
},
{
    id : 42,
    category:'Dosai',
    info: 'For fried rice, stir-fry cooked rice with vegetables, protein (like chicken or shrimp), soy sauce, and seasonings until well-blended and aromatic.',
    price: '200',
    image:'https://media.istockphoto.com/id/1430343827/photo/south-indian-breakfast-dosa.webp?b=1&s=170667a&w=0&k=20&c=eyfy4bdaqHv9xS8-emZcqiJx78Z2A2DpvcIzY9GuqdM=',
},
];

export default data;